version: '3'

services:
  nginx:
    build: .docker/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/tools
  tools:
    build: .docker/php-fpm
    container_name: tools
    volumes:
      - .:/var/www/tools
    ports:
      - 202:22
